const fs = require('fs');

/*///////////////
// ua-parser.mjs
//////////////*/

fs.writeFileSync('src/module/ua-parser.mjs',
`// Generated ESM version of UAParser.js
// DO NOT EDIT THIS FILE!
// Source: /src/ua-parser.js

` + fs.readFileSync('src/ua-parser.js','utf-8').replace(/\(func[\s\S]+strict\';/ig,'')
        .replace(/esversion\: 3/ig, 'esversion: 6')
        .replace(/\/[\/\s]+export[\s\S]+/ig,'export {UAParser};'),'utf-8');

/*/////////////////////
// ua-parser-enum.mjs
////////////////////*/

fs.writeFileSync('src/module/ua-parser-enum.mjs',
`// Generated ESM version of UAParser.js enums
// DO NOT EDIT THIS FILE!
// Source: /src/ua-parser-enum.js

` + fs.readFileSync('src/ua-parser-enum.js','utf-8')
        .replace(/module\.exports =/ig,'export'),'utf-8');

/*//////////////////////////
//  ua-parser-extension.mjs
/////////////////////////*/

fs.writeFileSync('src/module/ua-parser-extension.mjs',    
`// Generated ESM version of UAParser.js extensions
// DO NOT EDIT THIS FILE!
// Source: /src/ua-parser-extension.js

` + fs.readFileSync('src/ua-parser-extension.js','utf-8')
        .replace(/const UA.+\)/ig,'import UAParser from \'ua-parser-js\'')
        .replace(/module\.exports =/ig,'export'),'utf-8');