name: "CI: Build & Test"

on: [push, pull_request]

permissions:
  contents: read

jobs:
  run-test:
    name: "CI: Build & Test"
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        arch: [amd64]
        node-version: ['lts/iron', 'lts/jod', 'lts/krypton']
        include:
          - arch: ppc64le
            node-version: 20
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ matrix.node-version }}
      # setup-node must be called twice to correctly cache corepack-managed npm.
      # See: https://github.com/actions/setup-node/issues/531#issuecomment-3335630863
      - name: Enable Corepack
        shell: bash
        run: corepack enable npm
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          cache: npm
      - name: Install dependencies
        timeout-minutes: 10
        run: |
          echo "Running on ubuntu-latest-${{ matrix.arch }} with node version set as ${{ matrix.node-version }}"
          npm ci
      - name: Install Playwright browsers
        timeout-minutes: 10
        run: npx playwright install --with-deps
      - name: Run the test suite
        timeout-minutes: 10
        run: |
          npm run build+test
