name: "Publish: Docker"

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build-and-push:
    name: "Publish: Docker"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Extract version from release tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Check if version is >= 2.x
        id: version_check
        env:
          VERSION: ${{ steps.version.outputs.VERSION }}
        run: |
          if [[ $VERSION =~ ^([2-9]|[0-9]{2,})\. ]]; then
            echo "docker_support=true" >> $GITHUB_OUTPUT
          else
            echo "docker_support=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        if: steps.version_check.outputs.docker_support == 'true'
        uses: docker/setup-buildx-action@4c0219f9ac200910dac592e362cb6617a21cc34b # v3.0.0

      - name: Log in to Docker Hub
        if: steps.version_check.outputs.docker_support == 'true'
        uses: docker/login-action@343f7c4344506bcbf27e6996fab575069dac9d16 # v3.0.0
        with:
          username: faisalman
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: build
        if: steps.version_check.outputs.docker_support == 'true'
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3e4cbbdf0d34fa # v5.3.0
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            faisalman/ua-parser-js:${{ steps.version.outputs.VERSION }}
            faisalman/ua-parser-js:latest
          cache-from: type=registry,ref=faisalman/ua-parser-js:buildcache
          cache-to: type=registry,ref=faisalman/ua-parser-js:buildcache,mode=max
